services:
  format:
    image: mongoose-builder
    build:
      context: .
      dockerfile: Docker/Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: Docker/Scripts/format.sh
  builder:
    image: mongoose-builder
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: Docker/Scripts/build.sh